### PR TITLE
Mad Max: To Bin Or Not To Bin

### PR DESCRIPTION
**Pull request by o-smirnov**

### CODE REVIEW

**Comment by o-smirnov** [comment]
My tests pass. Over to you, @JSKenyon...

**Comment by JSKenyon** [comment]
@o-smirnov Busy fiddling at the moment. Installed correctly, ran through the nosetests. Just doing some other random testing. However, before we put this in, could you please update the relevant sections of the documentation. Was going to do it myself, but there are too many new options. I believe the only thing to be changed is the contents of parset.rst.

**Comment by JSKenyon** [comment]
Ok, this seems to work. Machine I tested on was heavily contested so cannot say anything about the speed up gained from binning. One thing I did notice is that with just 2 times and frequencies binned together, I saw noticeably worse subtraction of the dE sources. First image is with binning and mad max enabled (default options) while the second is with no binning and no mad max. I suspect this may be a result of the solution intervals and binning parameters interacting. I don't think it is a bug per-se, but something worth noting somewhere. If a chunk is 32 times by 32 channels, and it gets binned down to 16 times by 16 channels, I assume the solution intervals apply to the binned dimensions. So for a fair comparison, if the binning is increased by a factor of two, the solution interval must be reduced by a factor of two. @o-smirnov Is that correct? 

mad
nomad

**Comment by JSKenyon** [comment]
Ok, even reducing the intervals with the binned data, the sources with dEs are still more poorly subtracted. I guess it could also be attributed to the lower resolution on the G term. Oh well, still works as normal without binning - might be worth investigating the increase in speed vs the degradation in results. 
nomadli

**Comment by o-smirnov** [comment]
Yes, rebinning means the intervals need to be adjusted accordingly. Perhaps we need a feature to specify intervals in terms of seconds and MHz (we already have this option for the rebinning...)

@JSKenyon, for the above, did you follow up with an apply-only step? Reason being, when you solve and correct, the output data is upsampled from the rebinned resolution, which will always make things worse, especially off-axis.

And, of course, rebinning *will* affect solutions on distant sources most, because of smearing. The 3C147 data is not the best test case, as the original time/freq resolution is already pretty low, so smearing kicks in very quickly.

**Comment by JSKenyon** [comment]
> @JSKenyon, for the above, did you follow up with an apply-only step? Reason being, when you solve and correct, the output data is upsampled from the rebinned resolution, which will always make things worse, especially off-axis.

This is the sort of thing that really needs to be in the docs. This is because the full-resolution data no longer exists in the scope of the binned run, right? Completely fine, but we do need guides on how to use these options, particularly the interacting ones. 

The smearing hitting those sources hard is, as you say, not surprising. In fact, it suggests that the averaging is working correctly. Once the docs are brought up to date, I will happily hit the big green button and do a release.

**Comment by o-smirnov** [comment]
Hmmm, I wonder before we merge, should --flags-mad-xxx not be all renamed to --madmax-xxx? The ``[flags]`` section of the parset is getting a little fat.

**Comment by JSKenyon** [comment]
Yeah, that might be a good idea. Might also make the parset a bit easier to digest. We could also have a docs page where we have some sort of delineation between basic and advanced options. I think the -h is becoming a thing of nightmares for new users.

**Comment by o-smirnov** [comment]
We can always replace it with a "please help yourself" message a la @cyriltasse :)

**Comment by o-smirnov** [comment]
OK, I've split out a --madmax section and a --postmortem section. Sorry @IanHeywood @SpheMakh @bennahugo, if you've already started using the madmax options, you'll need to modify your scripts a little. A one-time pain in exchange for a clearer parset.

**Comment by o-smirnov** [comment]
OK I think I'm done documenting. @JSKenyon would you please check that my additions to parset.rst show up correctly?

**Comment by JSKenyon** [comment]
@o-smirnov I am going to merge this. I am happy that the code runs. Checking the docs on this branch is tough because the compiled code isn't checked in. Will merge into the release branch and check there. I can always fix any problems which appear. Once that is done I will do an actual release and update the PyPI version.

**Comment by JSKenyon** [comment]
@o-smirnov Yeah. :-) The docs have updated successfully. Will bump versions etc and release.

**Pull request merged**
