### PR TITLE
Madmax moreplots

### PR DESCRIPTION
**Pull request by bennahugo**
Initiate a PR to test CI

### CODE REVIEW

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
retest this please

**Comment by o-smirnov** [comment]
@JSKenyon, @bennahugo has added this to jenkins so now at least we have the confidence of tests passing. Could you please do a code review so we can approve the merge?

**Comment by JSKenyon** [comment]
Ok - too many changes for me to line-by-line. Looks sensible. Merging into master. I will wait about a week to do a release of a minor version/PyPI update. People building from master, please stress test these changes and report any bugs you find.

**Pull request merged**
