### PR TITLE
Pol cal robust merge

### PR DESCRIPTION
**Pull request by o-smirnov**
Another Big Gulp of a merge. Tests pass, dE subtraction passes, and it's twice as fast as it used to be for reasons I no longer remember.

### CODE REVIEW

**Comment by o-smirnov** [comment]
OK @gijzelaerr your homework for next week is to py3 this branch. It passes nosetests (except for an update to the test reference data that I'm currently stuggling to push out via LFS), and just needs a review from @JSKenyon to be merged into master. @JSKenyon starts on Monday so the two of you can work together on this.

**Comment by gijzelaerr** [comment]
yes supreme leader

**Comment by gijzelaerr** [comment]
so we are just going ignore the other py3 branch?

**Comment by o-smirnov** [comment]
I dunno, maybe try a quick merge of py3 into this one first, and see how much of a mess it makes?

**Comment by gijzelaerr** [comment]
probably equally messy as giving a toddler a flamethrower

**Comment by o-smirnov** [comment]
> probably equally messy as giving a toddler a flamethrower

You already did that when you introduced me to github.

**Comment by o-smirnov** [comment]
So the failing Jenkins test kind of sucks, but that's because LFS is fucking with me and won't let me push the updated reference data out. As long as it's just that one DE_DATA test failing, with 5e-6 tolerance, you're ok. I'll try to sort out LFS during the week.

**Pull request merged**
