### PR TITLE
Stimelation

### PR DESCRIPTION
**Pull request by o-smirnov**
I think we need to get our branches in order...

### CODE REVIEW

**Review by JSKenyon — APPROVED** [review]
LGTM!

**Comment by JSKenyon** [comment]
@o-smirnov No tests can currently run due to a lack of LFS credit. Could you possibly investigate what that looks like in the ratt-ru organisation?

**Comment by o-smirnov** [comment]
God, LFS is awful. Can we revise the tests to use a Dropbox link instead?

**Comment by o-smirnov** [comment]
ACtually let's see, it seems I only need to click a button to increase our free academic quota....

**Comment by o-smirnov** [comment]
ok to test

**Comment by JSKenyon** [comment]
> Actually let's see, it seems I only need to click a button to increase our free academic quota....

I just did a local LFS pull to rescue the test files while we have some bandwidth. Can investigate moving them to a Google Drive/Dropbox location at some point.

**Pull request merged**
