### PR TITLE
make pypi compatible

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by bennahugo** [comment]
I think we need to test this first - there was a reason to have it pinned to 0.6.1. 

I also think montblanc requires you to first install at least the CPU version of tensorflow - note it has to be 1.8.0
```
python3 -m pip install tensorflow==1.8.0
```

**Comment by bennahugo** [comment]
If I recall the code requires the old SPI specification so we need 0.6.1 unfortunately. Can you roll this back to that version (ie. <=0.6.1)

**Comment by gijzelaerr** [comment]
can someone then at least push 0.6.1 to pypi?

**Comment by bennahugo** [comment]
@sjperkins can you do this?

**Comment by JSKenyon** [comment]
I am unsure what changed in Montblanc - if someone can tell me, perhaps I can change the code to be compatible with the latest version. Failing that, I think it is relatively safe to hard pin the Montblanc version once 0.6.1 is on PyPI.

**Comment by sjperkins** [comment]
> @sjperkins can you do this?

I''m not going to give it immediate focus. From memory the issue was Tensorflow as a Montblanc build dependency -- this required a manual installation of tensorflow to build Montblanc (and hence Cubical) from source.

I think there may now be PEP517 concerns too. https://github.com/ska-sa/montblanc/pull/272. @bennahugo what was the requirement here for 0.6.4? DDFacet? Has anyone tried Cubical with 0.6.4.

@gijzelaerr you have "owner" on the pypi project. If you need this done quickly I would suggest trying to see if you can upload a 0.6.1 source tarball, but this may not lead to everything just working.

**Comment by gijzelaerr** [comment]
@sjperkins good point, thanks! upload 0.6.1 to pypi.

**Comment by bennahugo** [comment]
DDFacet works with the latest version @sjperkins. However one of the commits since 0.6.1 is a change in the SPI specification, which makes me think it will break cubical.

**Comment by bennahugo** [comment]
I think the user will just need to install tensorflow manually prior to installing cubical. It should crash out with a nice message to the user though so this I don't think is too much to ask from the user.

**Comment by sjperkins** [comment]
> @sjperkins good point, thanks! upload 0.6.1 to pypi.

I wouldn't do it straight away because once that 0.6.1 tarball is up, it can't be replaced. Perhaps see if you can pip install Cubical using the 0.6.1 source tarball somehow.

**Comment by gijzelaerr** [comment]
i mean uploadED, it is already uploaded.

**Comment by sjperkins** [comment]
> i mean uploadED, it is already uploaded.

OK! On second thoughts it wouldn't make sense to redo the tag contents now that it's been in the wild so long, so I think this is fine.

**Comment by bennahugo** [comment]
ok to test

**Comment by o-smirnov** [comment]
The spi specification is just a change in how the spectral polynomial is expressed, no? Can't we just have both, and an option to switch between? I mean ideally it's just two different kinds of spectral models, and the codebase ought to support both (as should codex).

**Comment by sjperkins** [comment]
Folks, a gentle reminder to:

1. check your github repo issue history and use descriptive searchable titles to make this easy.
2. Use the git blame feature to search through file changes (in this case, setup.py).

Using the above tools to do search through history it is possible to conclude that: Cubical has been using the "new" SPI functionality for a while:

* https://github.com/ratt-ru/CubiCal/commit/9afe9b0696b826c7e5cd2cd13999db1796d1d32d#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R156

Thus, 0.6.4 should work.

Other threads worth revisiting:

2. https://github.com/ratt-ru/CubiCal/issues/273
3. https://github.com/ratt-ru/CubiCal/pull/275

**Comment by sjperkins** [comment]
It looks from those threads that the idea was that Montblanc would be an optional dependency.

**Comment by bennahugo** [comment]
There is this commit: https://github.com/ska-sa/montblanc/commit/e8b2e7140e119f0d9e9caeb16f3fa66ec71406be
That I'm not sure of. Lets first get it pinned to 0.6.1 then we can worry about making potentially breaking changes.

**Comment by sjperkins** [comment]
> There is this commit: [ska-sa/montblanc@e8b2e71](https://github.com/ska-sa/montblanc/commit/e8b2e7140e119f0d9e9caeb16f3fa66ec71406be)
> after the 0.6.1 release that I'm not sure of. Lets first get it pinned to 0.6.1 then we can worry about making potentially breaking changes.

0.6.1 was probably the checkpoint release before the spectral index handling changed.

**Comment by sjperkins** [comment]
> 0.6.1 was probably the checkpoint release before the spectral index handling changed.

Correction, 0.6.1 tags the merge of the SPI changes (ddfacet) branch. So 0.6.4 should work because nothing has changed functionally since.

**Comment by sjperkins** [comment]
See you for the same discussion next year 😉

**Comment by sjperkins** [comment]
DDFacet's montblanc dependency is also >= 0.6.1

https://github.com/cyriltasse/DDFacet/blob/5289b7adb347826da00e68f14bba5765d29b8f3c/setup.py#L223

**Comment by bennahugo** [comment]
Yes sure, but this has been fixed on 0.6.1 - it may work with 0.6.3 but we
have to test it first by hand before we bump it up. I have changed the PR
to <= 0.6.1 for now. I also need to remove the py2 tests (which is why this
didn't pass yet)

**Comment by JSKenyon** [comment]
I think it is actually safe to change the version. I believe I actually already did in [another PR](https://github.com/ratt-ru/CubiCal/pull/432) which is awaiting review. Whilst I cannot say my testing was exhaustive, it certainly worked. I believe @ulricharmel has been using that branch without issue. So 0.6.4 should be fine.

**Review by JSKenyon — APPROVED** [review]

**Comment by JSKenyon** [comment]
I am happy to merge this - any concerned parties please voice your opinions before the end of the day, otherwise I will push the button.

**Comment by JSKenyon** [comment]
@gijzelaerr this has been merged if you want to try uploading to PyPI.

**Pull request merged**
