### PR TITLE
Pol cal

### PR DESCRIPTION
**Pull request by o-smirnov**
This still needs a few minor fixes and tests before merging -- also want to absorb #240 into it -- but it's almost ready, and it's quite a few changes.

@gijzelaerr would you please therefore base your py3 work (#242) on a branch off this branch.

### CODE REVIEW

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
stopping test:
```
_feed_actual_impl
    for (a, ph, ds, ad) in gen }
  File "/usr/local/lib/python2.7/dist-packages/montblanc/impl/rime/tensorflow/RimeSolver.py", line 513, in <dictcomp>
    for (a, ph, ds, ad) in gen }
  File "/usr/local/lib/python2.7/dist-packages/montblanc/impl/rime/tensorflow/RimeSolver.py", line 1101, in _get_data
    data = data_source.source(context)
  File "/usr/local/lib/python2.7/dist-packages/montblanc/impl/rime/tensorflow/sources/cached_source_provider.py", line 52, in memoizer
    array_cache[key] = method(context)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/TiggerSourceProvider.py", line 130, in point_stokes
    stokes[ind, :, :, 0] = source.flux.I[None, None]*spectrum
ValueError: An exception occurred while obtaining data from data source 'point_stokes'

'float' object has no attribute '__getitem__'

'point_stokes' data source information:
    Description: (I,Q,U,V) Stokes parameters.
    Units: Janskys
    Schema or abstract shape: ('npsrc', 'ntime', 'nchan', 4)
            where 'npsrc' is 'point sources'
            where 'ntime' is 'Timesteps'
            where 'nchan' is 'Channels'
    Global shape on this iteration: (24, 115, 64, 4)
    Local shape for this context: (24, 115, 64, 4)
    Lower extents within global shape: (0, 0, 0, 0)
    Upper extents within global shape: (24, 115, 64, 4)


Iteration information:
    Iterating over the ('ntime', 'nbl', 'npsrc') dimensions with
        global sizes of (115, 378, 24) in strides of (115, 378, 24).


This context is requesting the 'point_stokes' data source return an
array of shape '(24, 115, 64, 4)' and dtype '<type 'numpy.float32'>'.
This portion of data lies between the lower '(0, 0, 0, 0)'  and upper
'(24, 115, 64, 4)' extent of a global shape of '(24, 115, 64, 4)'. The
abstract shape of this data source is ('npsrc', 'ntime', 'nchan', 4).
[0m[0m
Loading /src/cubical/test/3C147-dE-apparent.lsm.html: Tigger sky model
```

**Comment by bennahugo** [comment]
Hangs indefinitely once montblanc dies.

**Comment by bennahugo** [comment]
@o-smirnov please review my changes

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
@o-smirnov on this note we should probably change the default to gain-diag. Unless the model can be trusted the solver shouldn't be solving a 2x2 matrix -- this is a wee bit dangerous for self calibration

**Comment by bennahugo** [comment]
And by dangerous I mean it will mop up diffuse polarized emission on boresight

**Comment by bennahugo** [comment]
@o-smirnov did you change the syntax for passing model lists?
```
 - 10:54:03 - main               [0.1/0.1 2.7/2.7 0.1Gb]  - list .............................................. = MODEL_WITHOUT_DES:/home/hugo/output/J1631-7507decal1-catalog.lsm.html.de_tagge
d.lsm.html@dE

....


 - 10:54:04 - data_handler       [0.2/0.2 2.4/2.8 0.1Gb] Using 1 model(s) for 3 directions(s)
 - 10:54:04 - main               [0.2/0.2 2.4/2.8 0.1Gb] Exiting with exception: ValueError(too many values to unpack)
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cubical/main.py", line 281, in main
    use_ddes=have_dd_jones and dde_mode != 'never')
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_data_handler.py", line 680, in init_models
    for imod, (dirmodels, weight_col) in enumerate(self.models):
ValueError: too many values to unpack
```

**Comment by o-smirnov** [comment]
I enhanced it, you can do things like ``MODEL_DATA-PEEL_MODEL_DATA:PEEL_MODEL_DATA`` now. Could you please pull and try again?

**Comment by bennahugo** [comment]
No same exception as before

**Comment by bennahugo** [comment]
I'm testing @ulricharmel's latest robust solver changes to check if things haven't changed somewhere else since @SpheMakh has built it into stimela 1.0.1

**Comment by o-smirnov** [comment]
OK, could you please re-run with ``--debug-pdb 1``, and then ``p self.models`` once it drops into the debugger, and post the results?

**Comment by bennahugo** [comment]
That branch runs through until the segfault makes the process hang at
```
(venvstimela) > $ tail output/J1631-7507.log                                                                                                                                        [±master ●●]
 - 12:39:35 - solver             [x13] [0.3/1.1 3.1/3.8 1.7Gb] D0T1F43 dd: 1500 iters, conv 83.33%, g/fl 39.22%, d/fl 44.12%, PGE 0.112 0.0 0.236, NFPGE 2 0 6, stall 98.88%, chi^2 1.572 -> 1.326 (1.32), noise 0.786 -> 0.788
 - 12:39:35 - solver             [x13] [0.3/1.1 3.1/3.8 1.7Gb] D0T1F43 solver flags GOOB:27(26.47%) GVAR:8(7.84%) ILLCOND:3(2.94%) LOWSNR:2(1.96%): 0 (0.00%) new data flags
 - 12:39:35 - solver             [x49] [0.3/1.0 3.0/3.8 1.7Gb] D0T1F37 dd: 1500 iters, conv 66.67%, g/fl 46.08%, d/fl 44.12%, PGE 0.584 0.0 0.967, NFPGE 4 0 7, stall 60.88%, chi^2 1.955 -> 1.759 (1.673), noise 0.71 -> 0.728
 - 12:39:35 - solver             [x49] [0.3/1.0 3.0/3.8 1.7Gb] D0T1F37 solver flags GOOB:31(30.39%) GVAR:11(10.78%) ILLCOND:3(2.94%) LOWSNR:2(1.96%): 0 (0.00%) new data flags
 - 12:39:40 - solver             [x26] [0.3/1.1 3.1/3.8 1.7Gb] D0T1F31 dd: 1500 iters, conv 83.33%, g/fl 18.63%, d/fl 76.47%, PGE 0.107 0.0 0.0, NFPGE 1 0 0, stall 16.38%, chi^2 1.816 -> 1.679 (1.594), noise 0.975 -> 1.0
 - 12:39:40 - solver             [x26] [0.3/1.1 3.1/3.8 1.7Gb] D0T1F31 solver flags GOOB:4(3.92%) GVAR:1(0.98%) LOWSNR:14(13.73%): 0 (0.00%) new data flags
 - 12:39:40 - solver             [x62] [0.3/1.1 3.0/3.8 1.7Gb] D0T1F35 dd: 1500 iters, conv 66.67%, g/fl 16.67%, d/fl 76.47%, PGE 0.0703 0.0 0.406, NFPGE 0 0 2, stall 72.38%, chi^2 1.999 -> 1.857 (1.709), noise 0.756 -> 0.787
 - 12:39:40 - solver             [x62] [0.3/1.1 3.0/3.8 1.7Gb] D0T1F35 solver flags GOOB:15(14.71%) GVAR:2(1.96%): 0 (0.00%) new data flags
 - 12:39:40 - main               [0.2/0.2 2.8/2.9 1.7Gb] finished processing tile #2/16
 - 12:39:40 - main               [0.2/0.2 2.8/2.9 1.7Gb] waiting for I/O on tile #3/16
```

**Comment by o-smirnov** [comment]
I assume you're seeing a SEGV in the I/O thread? I think I fixed it in ``polcal``, but obviously not yet on the other branch. If you want to try the fix, it's literally six characters: https://github.com/ratt-ru/CubiCal/pull/243/commits/a90db9bbcb41431862e9a9b0e9a3174e897b3a4c#diff-af226e4f22a7b864d3f4d9f3b156b5bcR830

Just add a ``False`` to the if statement so it never invokes ``putcolslice``, and rather does a full ``putcol`` each time. I think there's a bug in ``putcolslice`` -- it was segfaulting deep inside casacore's guts.

**Comment by bennahugo** [comment]
INFO:STIMELA:Starting container [calibrate_target_0-140327676925296155480352234]. Timeout set to -1. The container ID is printed below.
Running: docker start -a calibrate_target_0-140327676925296155480352234
Running: gocubical --sol-jones dd --weight-column WEIGHT --out-subtract-dirs 1: --out-column SUBTRACTED_DATA --out-mode sr --data-time-chunk 100 --model-beam-pattern /home/hugo/output/'MeerKAT_VBeam_10MHz_53Chans_$(corr)_$(reim).fits' --model-beam-m-axis Y --dd-type complex-diag --dd-clip-high 1.2 --data-ms /home/hugo/msdir/COMBINED.J1631-7507.1GC.ms --out-casa-gaintables 0 --model-list MODEL_WITHOUT_DES:/home/hugo/output/J1631-7507decal1-catalog.lsm.html.de_tagged.lsm.html@dE --data-column CORRECTED_DATA --dd-dd-term 1 --dd-fix-dirs 0 --model-ddes auto --madmax-enable 0 --dist-nworker 0 --model-beam-l-axis X --flags-apply -cubical --out-plots 1 --out-name /home/hugo/output/J1631-7507 --sol-diag-diag 1 --dd-clip-low 0 --flags-auto-init legacy --dd-max-iter 1000 --sol-max-bl 0 --dd-freq-int 16 --dd-time-int 40 --dist-ncpu 64 --data-freq-chunk 16 --sol-min-bl 110.0
Traceback (most recent call last):
  File "/usr/local/bin/gocubical", line 6, in <module>
    from cubical.main import main
  File "/usr/local/lib/python2.7/dist-packages/cubical/main.py", line 42, in <module>
    from cubical import workers
  File "/usr/local/lib/python2.7/dist-packages/cubical/workers.py", line 8, in <module>
    from cubical import solver
  File "/usr/local/lib/python2.7/dist-packages/cubical/solver.py", line 418
    obser_arr, model_arr, flags_arr, np.sqrt(weight_arr)
    ^
IndentationError: unexpected indent

**Comment by bennahugo** [comment]
- 10:35:33 - data_handler       [io] [0.3/0.5 3.0/3.1 9.6Gb] model 0 weights 0: reading from WEIGHT
 - 10:35:33 - main               [io] [0.3/0.5 3.0/3.1 9.6Gb] I/O handler for load 0 save None failed with exception: column WEIGHT has an invalid shape (8944, 4) (expected (8944, 1366, 2))
 - 10:35:33 - main               [io] [0.3/0.5 3.0/3.1 9.6Gb] Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cubical/workers.py", line 431, in _io_handler
    tile.load(load_model=load_model)
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/ms_tile.py", line 668, in load
    raise RuntimeError("column {} has an invalid shape {} (expected {})".format(weight_col, wcol.shape, obvis0.shape))
RuntimeError: column WEIGHT has an invalid shape (8944, 4) (expected (8944, 1366, 2))
 - 10:35:33 - main               [0.2/0.2 2.6/2.8 9.6Gb] Exiting with exception: RuntimeError(column WEIGHT has an invalid shape (8944, 4) (expected (8944, 1366, 2)))
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cubical/main.py", line 395, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/usr/local/lib/python2.7/dist-packages/cubical/workers.py", line 208, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts)
  File "/usr/local/lib/python2.7/dist-packages/cubical/workers.py", line 258, in _run_multi_process_loop
    if not done or not io_futures[itile].result():
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
RuntimeError: column WEIGHT has an invalid shape (8944, 4) (expected (8944, 1366, 2))

**Comment by bennahugo** [comment]
(this is full polarization data)

**Comment by bennahugo** [comment]
and the following in complex-2x2 mode:
```
ValueError: could not broadcast input array from shape (8944,4) into shape (8944,1366,4)
 - 10:39:11 - main               [0.2/0.2 2.6/2.8 0.2Gb] Exiting with exception: ValueError(could not broadcast input array from shape (8944,4) into shape (8944,1366,4))
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cubical/main.py", line 395, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/usr/local/lib/python2.7/dist-packages/cubical/workers.py", line 208, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts)
  File "/usr/local/lib/python2.7/dist-packages/cubical/workers.py", line 258, in _run_multi_process_loop
    if not done or not io_futures[itile].result():
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
ValueError: could not broadcast input array from shape (8944,4) into shape (8944,1366,4)
```

**Comment by bennahugo** [comment]
> /usr/local/lib/python2.7/dist-packages/cubical/machines/complex_2x2_machine.py(134)compute_js()
-> return jhr, jhjinv, flag_count
(Pdb)
> /usr/local/lib/python2.7/dist-packages/cubical/machines/complex_2x2_machine.py(134)compute_js()
-> return jhr, jhjinv, flag_count
(Pdb)
> /usr/local/lib/python2.7/dist-packages/cubical/machines/complex_2x2_machine.py(134)compute_js()
-> return jhr, jhjinv, flag_count
(Pdb)
 - 11:31:59 - main               [0.2/0.2 2.8/2.8 2.1Gb] Exiting with exception: BdbQuit()
 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cubical/main.py", line 395, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/usr/local/lib/python2.7/dist-packages/cubical/workers.py", line 208, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts)
  File "/usr/local/lib/python2.7/dist-packages/cubical/workers.py", line 281, in _run_multi_process_loop
    stats = future.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
BdbQuit

**Comment by o-smirnov** [comment]
Ugh, forgot to take out the breakpoint. Could've sworn I'd commented it out. Senility setting in I guess.

**Comment by bennahugo** [comment]
It looks like only the diag-diag option is affected. I've filled the WEIGHT_SPECTRUM column using TSys estimates and it looks like it is running, so only the WEIGHT mode is buggy

**Comment by bennahugo** [comment]
spoke too soon full 2x2 is also affected

**Pull request merged**
