### PR TITLE
Fixes #273

### LINKED ISSUE #273: do we really need a hard montblanc/tensorflow dependency?
The code has an exception handler around the ``import montblanc`` statements, and runs fine without Montblanc, unless an LSM is selected. But the new ``setup.py`` now crashes out if montblanc is not installed (complains about tensorflow). Is it wise to have this hard coupling?

### PR DESCRIPTION
**Pull request by bennahugo**

### CODE REVIEW

**Comment by bennahugo** [comment]
Tested on 16.04, 18.04 and 18.04 py3

**Comment by o-smirnov** [comment]
Hmmm, not to [pull a Henry II](https://en.wikipedia.org/wiki/Will_no_one_rid_me_of_this_turbulent_priest%3F), but let's discuss...

Maybe on by default, but with an option to disable?

**Comment by bennahugo** [comment]
can't do it that way around I'm afraid. It is either an optional dependency or a hard dependency, pip doesn't differentiate

**Comment by bennahugo** [comment]
That said you can always force pip not to install dependencies: --no-dependencies

**Pull request merged**
