### PR TITLE
OMP support. Bigger, better, faster.

### PR DESCRIPTION
**Pull request by o-smirnov**
This adds in the shiny new OMP-enabled kernels. Also fixes a whole load of recent issues (#168, #169, #170). Also adds things like fully diagonal modes (``--sol-diag diag True`` and ``--g-type complex-diag``, for example).

I have also added acceptance tests. Now that people are actually using the thing in anger, we need a modicum of confidence for future updates. Nosetests will now do something useful: 

* kernels are verified against the frozen reference kernels

* a small subset of the 3C147 data is used to test solvers, and verify corrected residuals against a set of reference columns. The reference data is checked in with git lfs (perhaps unwisely...)

@bennahugo once this goes in, we can add the testing to jenkins. The tests only take a few minutes. (TODO: add a DD-solution test).

### CODE REVIEW

**Comment by o-smirnov** [comment]
Sorry @JSKenyon, this is going to be an utter bastard to review. :) Just try to look for things that are obviously wrong.

I have run the new acceptance tests against residuals generated by the current master (with #168 and #170 fixed), and everything passes (full complex, phase only, B+G chain, slopes and a plane). The only thing not tested is DD solutions -- maybe you want to check that with your own tests, for sanity's sake.

**Comment by o-smirnov** [comment]
Do not merge yet @JSKenyon, I've added a dE test and it's not passing...

**Comment by o-smirnov** [comment]
@JSKenyon, file another one under the "how did this ever work" category... Surely [this](https://github.com/ratt-ru/CubiCal/blob/master/cubical/kernels/cyfull_complex.pyx#L88) ought to be doing ``gd = d%g_dir`` just like [this](https://github.com/ratt-ru/CubiCal/blob/master/cubical/kernels/cyfull_complex.pyx#L523)? 

Perhaps the answer is that this version of ``compute_residuals()`` never got called in a chain context (which is the only situation where you can have n_dir!=g_dir).

**Comment by JSKenyon** [comment]
@o-smirnov I think you figured it out yourself. As you say, there is no need to deal with mismatched direction dimensions in the single term case. I believe the purpose of all the chain implementations was to take the extra requirements into account.

**Comment by o-smirnov** [comment]
OK, this now passing everything I can throw at it. So unless you get it to break, @JSKenyon, this should be merged in.

@bennahugo @IanHeywood, if you're feeling brave, you can try it with MeerKAT data again. Many fixes to slopes and such. Plus, new options: ``--dist-nworker`` gives the number of worker processes to launch. So if you have, say, 32 cores, but only enough RAM to process 4 chunks at a time, use --dist-ncpu 32 --dist-nworker 4, and you'll have 4 workers with up to 8 OMP threads each.

There's also --dist-nthread to make this explicit, and --montblanc-threads to limit the CPUs the predict uses.

**Comment by JSKenyon** [comment]
@IanHeywood Yep. Make sure sure the kernels recompile though. 

@o-smirnov Testing it out. Some weirdness with the dist options. If I do `--dist-ncpu 33 --dist-nworker 4`, I get 32 worker processes with one OMP thread each (total 32 cores).  If I do `--dist-ncpu 33 --dist-nworker 4 --dist-nthread 8`, I get 32 workers with 8 threads each (total 256 cores). This doesn't seem right. To get the behaviour I want, I had to do `--dist-ncpu 5 --dist-nworker 4 --dist-nthread 8`, for a total of 4 workers with 8 threads each. I almost feel like one of `--dist-npu` and `--dist-nworker` is redundant. I feel like simply specifying `--dist-nworker 5 --dist-nthread 8` should imply use of `(nworker - 1)*nthread` cores. As usual, the extra worker is the I/O process. Thoughts?

**Comment by JSKenyon** [comment]
@o-smirnov In general, my results seem fine. Minor discrepancies with some of my older images, but that could be attributed rounding errors (order of operation changes). I also see slight differences between the results of small chunks with many processes and big chunks with few processes and many threads. Again, these are at the 10^-6 level which would be consistent with rounding at single precision.

**Comment by o-smirnov** [comment]
Yeah, I think this line is where I screwed up the ncpu/nworker logic: https://github.com/ratt-ru/CubiCal/blob/omp-support/cubical/main.py#L352

It's a little redundant I agree, but my motivation for keeping ``--dist-ncpu`` is because I want to have automatic worker/thread selection logic at some point in the future, so the user should only need to specify how many cores to occupy. ``nworker`` and ``nthread`` would then be "power user" options for people who want explicit control. So how about this proposal:

* ncpu=nworker=nthread=0 (i.e. defaults): no paralellism at all

* nworker>0 and nthread>0: ignore the ncpu setting ("power user mode")

* ncpu>0, nworker=nthread=0: determine workers and threads automatically (in the future), but for now use nworker=ncpu and nthread=1.

* ncpu>0 nworker>0 nthread=0: use nthread=ncpu/nworker. 

* ncpu>0 nworker=0 nthread>0: use nworker=ncpu/nthread

**Comment by o-smirnov** [comment]
OK, I've pushed changes to the --dist options, as proposed above. The rather convoluted logic is here: https://github.com/ratt-ru/CubiCal/blob/omp-support/cubical/workers.py#L19. It is arguably **too** flexible, but I'd rather expose all the options for now. When we get more experience with what works well and what doesn't, we can perhaps simplify the options. In any case a "dumb" user won't go too far wrong by simply setting ``--dist-ncpu`` and ignoring the rest.

The log messages will report on the distribution strategy it selects.

Note that ``--dist-nworker`` refers to the number of solver workers, the I/O worker is implicitly a +1. I just find it easier to think about it that way...

**Comment by o-smirnov** [comment]
OK, after a lot of frustrating screwing around, I can only conclude that tensorflow does something funky with OMP -- the standard way of setting thread affinities causes it to hang. For example, if we try to pin Montblanc to 16 cores by setting GOMP_CPU_AFFINITY, tensorflow launches 3 (??) threads and hangs.

On the other hand, it seems to respect OMP_NUM_THREADS and OMP_THREAD_LIMIT. So ``--montblanc-threads`` seems to work, i.e. it restricts it to the specified number of threads (at least on stills), it just schedules them all over the place.

 The solver workers respect GOMP_CPU_AFFINITY though. So, the status for now:

* I've disabled the ``--dist-pin-io`` option when Montblanc is in use (it can still pin the I/O worker to one core if you're not using Montblanc)

* ``--montblanc-threads`` seems to restrict Montblanc parallelism (fixes #159), it just schedules threads all over the place.

* solver workers respond as designed.

I propose we merge (@JSKenyon, please do another sanity test just to be sure, I pushed my fixes which I think replicate the fixes we made in your working tree on crosby), and leave the CPU pinning of tensorflow to better days. Maybe @sjperkins will discover a solution.

**Comment by JSKenyon** [comment]
@o-smirnov OK, hanging is fixed. My tests are working but, for any users reading this, do not expect the threading to give significant performance improvements. I have not profiled it rigorously, but inspection of htop suggests that the unthreaded Python glue is the performance killer on huge chunks. This may well be something we can improve on in a future version using Numba. I am pushing the button now, and will shortly do a release and update PyPi. Users, please open issues for the bugs we almost certainly missed.

**Comment by sjperkins** [comment]
I aim to move away from using OpenMP in tensorflow once https://github.com/tensorflow/tensorflow/issues/13308 is fixed. Tensorflow has a couple of it's own thread pools described here https://stackoverflow.com/a/41233901.

**Pull request merged**
