### PR TITLE
Apply gains to autocorrelations when forming corrected data/residuals.

### PR DESCRIPTION
**Pull request by JSKenyon**
@bennahugo could you please test drive this? I have sanity checked it locally, but you may want to confirm that it is producing what you expect.

### CODE REVIEW

**Comment by JSKenyon** [comment]
retest this please

**Comment by JSKenyon** [comment]
Tests cannot pass at present. [See this SO](https://stackoverflow.com/questions/65896334/python-pip-broken-with-sys-stderr-writeferror-exc/66103179#66103179). I know we decided that python2.7 needed to burn, so should we remove that part of the tests?

**Comment by o-smirnov** [comment]
Yeah we were already going to drop it in https://github.com/ratt-ru/CubiCal/pull/424 anyway. Which, BTW, really ought to get merged now. But let's do this one first!

**Comment by bennahugo** [comment]
Sure I will try it next week - a bit swamped monitoring the current science
observations. Thanks Jon.

**Comment by bennahugo** [comment]
As discussed this removes the OMT response but neither the Tsys contribution from Tlna or Tspil which are both correlated powers that are frequency dependent on these products @landmanbester. I don't see a reason not to at least remove the OMT response from them though? The other Tsys factors have to be determined by other means - ie on/off observation or another more complicated mechanism to block off the power from the horn in switching systems - these are in very old telescopes, but I don't know if they are actually still in use anywhere.

**Pull request merged**
