### PR TITLE
Custom spectral expressions for montblanc

### PR DESCRIPTION
**Pull request by sjperkins**
The return...

### CODE REVIEW

**Comment by sjperkins** [comment]
jenkins test this please

**Comment by sjperkins** [comment]
So the tests fall over on the 1 model, 10 directions case because the tolerance is above the allowed 1e-6 threshold:

```
Loading /src/cubical/test/3C147-dE-apparent.lsm.html: Tigger sky model
*** max diff between CORRECTED_DATA and DE_DATA is 7.6667383837e-06
ERunning python /src/cubical/test/benchmark/kernel_timings.py cyphase_only cyphase_only_omp --reference cyphase_only_reference --omp 4 --diag --nd 1 --nd 5 --nf 50 --nt 50 --ti 1 --fi 1
```

Previously, this case only succeeded because because nan's were being produced for the test case . However, if you compared the other "max diff" values for the other case in the test output for this [PR](https://jenkins.meqtrees.net/job/cubical-pr/27/console) and the [first that introduced montblanc](https://jenkins.meqtrees.net/job/cubical-pr/9/console) you'll see that the values are precisely the same.

I'm guessing nan's crept in because the [reference frequency can be be set to zero](https://github.com/ratt-ru/CubiCal/blob/77b2cd0e743c24a077dfb99f1b745e95a186ac03/cubical/data_handler/TiggerSourceProvider.py#L185). -- This probably explains why the tolerance is out for dE test -- I've set the reference frequency to 1 if not present. There are indeed sources with missing reference frequency

Could I have a review on this test case and advice on how to handle the missing ref freqs? The freq0 for the 3C147-dE-apparent.lsm.html is missing.

**Comment by o-smirnov** [comment]
Oops! I think there was logic in Tigger somewhere to take the ref freq from the first source if it was missing for the other sources, but obviously it's gone awry.

And of course ``diff > tolerance`` is False if diff is NaN, since a Nan is not greater than nor less than any number. So indeed the tests were passing.

Obviously we need to also need to add a check for NaNs and fail the test if any are detected.... I'll get on it.

**Comment by o-smirnov** [comment]
Even more correct would be to use a flat spectrum if the reference freq is missing... Anyway, good catch @sjperkins, thanks!

**Comment by o-smirnov** [comment]
Trying to get back into this now... are the tests still failing?

I can see you added code to use the "last spotted" reference frequency if missing. What exactly was the Montblanc's old behaviour w.r.t. missing reference frequency? Could that be the source of the difference?

I still contend that falling back to a flat spectrum is the more correct thing to do.

**Comment by sjperkins** [comment]
> Trying to get back into this now... are the tests still failing?

"Yes", but only because there were nans that caused the test to pass. For the cause of the nans, read on.

> I can see you added code to use the "last spotted" reference frequency if missing. What exactly was the Montblanc's old behaviour w.r.t. missing reference frequency? Could that be the source of the difference?

Well Cubical's previous behaviour w.r.t. missing reference frequency was to set it to 0, which produced infs which led to nans...

Also, from fuzzy memory last year, the individual test looped over about 4 or 5 cases, the last of which was the DDE case. The DIE case values match exactly to the commit this PR is based on, while the DDE case (formerly producing nans) now fails because the difference is outside the accepted tolerance.

> I still contend that falling back to a flat spectrum is the more correct thing to do.

OK can change this to be the default.

**Comment by o-smirnov** [comment]
> while the DDE case (formerly producing nans) now fails because the difference is outside the accepted tolerance.

No that can't be the whole story. The reference DE_DATA does not contain NaNs... so we *weren't* producing NaNs at some point in the past, then at some point we started producing them but the tests kept passing because ``NaN > anything`` is False... so now we need to produce non-NaNs that are consistent with our old non-NaNs. :)

**Comment by o-smirnov** [comment]
> Could I have a review on this test case and advice on how to handle the missing ref freqs? The freq0 for the 3C147-dE-apparent.lsm.html is missing.

Ah I see now where we got the misunderstanding (I was confused how freq0 could be missing...) The first six sources in that model have a proper ``spectrum`` attribute with freq0 and spi. The remainder have no ``spectrum`` attribute at all, which is meant to be interpreted as no spectral variation i.e. flat spectrum. However the exception handler in the provider attempts to set up both properties anyway -- ending up with spi=freq0=0 when the spectrum is missing. The correct thing to do would have been to use spi=0, freq0=(anything !=0). ANyway, easily fixed -- let's see if this makes the tests pass.

**Comment by sjperkins** [comment]
The zero reference frequency was introduced two years ago as part of PR https://github.com/ratt-ru/CubiCal/pull/31 in this commit https://github.com/ratt-ru/CubiCal/blob/1b3891b1da5e78e3e74755ce986e37756551f4ae/cubical/TiggerSourceProvider.py#L115-L119 

The test case was introduced in the middle of last year as part of PR  https://github.com/ratt-ru/CubiCal/pull/171 in commit https://github.com/ratt-ru/CubiCal/blob/15470c65e3cda367afc50a4169ae6253c16ec3d2/test/d147_test.py#L30-L42 

It doesn't look like the tolerance comparison has changed since [the introduction of the test case](https://github.com/ratt-ru/CubiCal/blame/master/test/d147_test.py#L50) .

This is why I think that the test case has always silently succeeded due to nans.

**Comment by o-smirnov** [comment]
Here's a plot of the *difference between the Montblanc model visibilities* (master versus ddfacet branches) on my laptop. X axis is |uv|.

image

**Comment by o-smirnov** [comment]
And here's a similar plot for the difference between model visibilities computed with the ddfacet branch on my laptop and on stills:

image

And the difference between model visibilities computed with the master branch on my laptop and on stills:

image

Seems to have the same structure?

And, for completeness, the difference between the master versus ddfacet branches on stills.

image

**Comment by bennahugo** [comment]
@o-smirnov @sjperkins I think I changed the way parallactic angles were applied in the ddfacet branch. They are now computed per antenna (the difference in ECEF coordinates gives a small (few degree error) on the P jones application). Also remember to turn parallelization off in the test - could very well just be machine error at that level

**Comment by bennahugo** [comment]
(I can't remember if those changes were checked in or not though.. I was still trying to track down the pointing correction errors at the time)

**Comment by o-smirnov** [comment]
@bennahugo, I don't think it's to do with PA. These are circular feeds, so PAs should only affect the off-diagonal terms -- which actually match up quite well (see plots above). The difference is in the real part of the on-diagonals...

**Comment by o-smirnov** [comment]
OK nevermind. @sjperkins your hunch was correct. I have re-instated the dtype=double option, and now the difference between the master+master and pol-cal+ddfacet model visibilities is a big fat 0.000000. 

I guess the lesson is, we just need to fix Montblanc's dtype to double...

**Pull request merged**
