### PR TITLE
Added different slope modes for slope solvers. Experimental.

### PR DESCRIPTION
**Pull request by JSKenyon**
@bennahugo This adds a new option to the gain section of the parset - "slope-type" - which defaults to using frequency directly. Other modes are inverse, for 1/nu behaviour and inverse-squared for 1/nu**2 behaviour. These are currently very experimental, so let me know if you run into problems. Currently, these modes only work for frequency slopes/planes.

### CODE REVIEW

**Comment by bennahugo** [comment]
Thanks @JSKenyon I'm still doing simulations on how to bandpass the bandpass first because of massively bright field substructure. This will probably take a few weeks to analyse correctly

**Comment by JSKenyon** [comment]
@bennahugo There is no time pressure on this one, so no need to rush. Hopefully it will just work.

**Comment by KshitijT** [comment]
Awesome ! I'll see if I can try it out before Ben does. ;)

**Comment by o-smirnov** [comment]
This sleeping giant needs a wake-up call.

**Review by o-smirnov — APPROVED** [review]
Time to merge this...

**Comment by JSKenyon** [comment]
This needs to be reopened as a new PR @o-smirnov. I cannot do it from my Windows machine. If you can wait, I will take care of it on Monday.

**Comment by o-smirnov** [comment]
No rush at all. I might figure out the problem by Monday... might already have in fact...

**Comment by o-smirnov** [comment]
Aha! I think I see the problem. Anyway, I merged it into the ``noxcal`` branch. Let me debug that.

**Pull request merged**
