### PR TITLE
fixes #274 and #279. Also includes timings to shed light on #277 discussion

### LINKED ISSUE #274: 16.04 py2: Exiting with exception: RuntimeError(PycValueHolder: unknown python data type)
New master crashes on 16.04/py2:
```
- 08:47:05 - data_handler       [2.6/14.9 8.1/20.5 7.8Gb]   inserting new column SC_PHASE_DATA
 - 08:47:05 - main               [2.6/14.9 8.1/20.5 7.8Gb] Exiting with exception: RuntimeError(PycValueHolder: unknown python data type)
 Traceback (most recent call last):
  File "/home/oms/projects/CubiCal/cubical/main.py", line 480, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/home/oms/projects/CubiCal/cubical/workers.py", line 212, in run_process_loop
    return _run_single_process_loop(ms, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/home/oms/projects/CubiCal/cubical/workers.py", line 351, in _run_single_process_loop
    tile.save(final=tile is tile_list[-1])
  File "/home/oms/projects/CubiCal/cubical/data_handler/ms_tile.py", line 1149, in save
    added = self.dh._add_column(self.dh.output_column)
  File "/home/oms/projects/CubiCal/cubical/data_handler/ms_data_handler.py", line 1374, in _add_column
    self.ms.addcols(desc, dminfo)
  File "/home/oms/.venv/cc/lib/python2.7/site-packages/python_casacore-3.0.0-py2.7-linux-x86_64.egg/casacore/tables/table.py", line 1228, in addcols
    self._addcols(tdesc, dminfo, addtoparent)
RuntimeError: PycValueHolder: unknown python data type
```
I'm afraid we have to support that combo for a bit yet, so let's figure out what this is. I suspect the python-casacore version installed by pip needs to be backed off to match the 16.04 casacore?

### PR DESCRIPTION
**Pull request by o-smirnov**

### CODE REVIEW

**Comment by o-smirnov** [comment]
Actually let's not merge yet, the last change causes more troubles than it solves...

**Comment by bennahugo** [comment]
you need to run all three checks manually because the build system is down.
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [   
        {
            "label": "Build Cubical",
            "type": "shell",
            "command": "source ../venv/bin/activate && python setup.py gocythonize && python setup.py build && deactivate",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Build Cubical Docker 3",
            "type": "shell",
            "command": "docker build -f .jenkins/1604.py2.docker -t cubicalkern3 .",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Test Cubical Docker 3",
            "type": "shell",
            //"command": "docker run --rm -m 100g --cap-add sys_ptrace --memory-swap=-1 --shm-size=150g --rm=true --entrypoint /bin/bash cubicalkern3 -c 'cd /src/cubical && apt-get install -y git && pip install -r requirements.test.txt && nosetests test'",
            "command": "docker run --rm -m 100g --cap-add sys_ptrace --memory-swap=-1 -v /tmp:/root/tmp --shm-size=150g --rm=true --entrypoint /bin/bash cubicalkern3 -c 'cd /src/cubical/test && tar zxvf SUBSET-D147-output.MS.tgz && nosetests d147_test.py'",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Build Cubical Docker 5",
            "type": "shell",
            "command": "docker build -f .jenkins/1804.py2.docker -t cubicalkern5 .",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Test Cubical Docker 5",
            "type": "shell",
            //"command": "docker run --rm -m 100g --cap-add sys_ptrace --memory-swap=-1 --shm-size=150g --rm=true --entrypoint /bin/bash cubicalkern3 -c 'cd /src/cubical && apt-get install -y git && pip install -r requirements.test.txt && nosetests test'",
            "command": "docker run --rm -m 100g --cap-add sys_ptrace --memory-swap=-1 -v /tmp:/root/tmp --shm-size=150g --rm=true --entrypoint /bin/bash cubicalkern5 -c 'cd /src/cubical/test && tar zxvf SUBSET-D147-output.MS.tgz && nosetests d147_test.py'",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Build Cubical Docker 5py3",
            "type": "shell",
            "command": "docker build -m 16g --no-cache -f .jenkins/1804.py3.docker -t cubicalkern5py3 .",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "Test Cubical Docker 5py3",
            "type": "shell",
            //"command": "docker run --rm -m 100g --cap-add sys_ptrace --memory-swap=-1 --shm-size=150g --rm=true --entrypoint /bin/bash cubicalkern3 -c 'cd /src/cubical && apt-get install -y git && pip install -r requirements.test.txt && nosetests test'",
            "command": "docker run --rm -m 100g --cap-add sys_ptrace --memory-swap=-1 -v /tmp:/root/tmp --shm-size=150g --rm=true --entrypoint /bin/bash cubicalkern5py3 -c 'cd /src/cubical/test && tar zxvf SUBSET-D147-output.MS.tgz && nosetests d147_test.py'",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
    ]
}
```

**Comment by JSKenyon** [comment]
@o-smirnov I have merged master into this branch. Could you please remove what needs to be removed? I looked but am uncertain exactly what has to go.

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
ok to test

**Comment by JSKenyon** [comment]
@o-smirnov I think that pieces of this have been fixed/changed in master. Would you mind revising the PR if it is still needed?

**Comment by JSKenyon** [comment]
What is that status on this?

**Comment by o-smirnov** [comment]
It's still useful. If the tests pass, we merge.

**Pull request merged**
