### PR TITLE
Retry adding wisdom

### PR DESCRIPTION
**Pull request by bennahugo**
Reverts ratt-ru/CubiCal#363

### CODE REVIEW

**Comment by bennahugo** [comment]
sorry about that clicked the wrong button

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
retest this please

**Comment by JSKenyon** [comment]
retest this please

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
```
---> 8a6f80ab3d43
Step 26/27 : ENTRYPOINT ["gocubical"]
 ---> Running in 76786abfa7b8
Removing intermediate container 76786abfa7b8
 ---> ffa27c821e2e
Step 27/27 : CMD ["--help"]
 ---> Running in 8c8acfa55051
Removing intermediate container 8c8acfa55051
 ---> 4db8a1be56f7
Successfully built 4db8a1be56f7
Successfully tagged cubical.1604.py2:1
Traceback (most recent call last):
  File "/usr/local/bin/gocubical", line 5, in <module>
    from cubical.main import main
  File "/usr/local/lib/python2.7/dist-packages/cubical/main.py", line 34, in <module>
    from cubical.data_handler.wisdom import estimate_mem
  File "/usr/local/lib/python2.7/dist-packages/cubical/data_handler/wisdom.py", line 74
    tot_sys_mem), file=log)
                      ^
SyntaxError: invalid syntax
Build step 'Execute shell' marked build as failure
Setting status of a0a466e203d97adfb2c105feebd46e9325d37f37 to FAILURE with url https://jenkins.meqtrees.net/job/PR_cubical/1/ and message: 'Build finished. '
Finished: FAILURE
```
@JSKenyon syntax error

**Comment by JSKenyon** [comment]
retest this please

**Comment by JSKenyon** [comment]
retest this please

**Comment by JSKenyon** [comment]
retest this please

**Comment by JSKenyon** [comment]
retest this please

**Comment by JSKenyon** [comment]
retest this please

**Comment by JSKenyon** [comment]
retest the please

**Comment by JSKenyon** [comment]
retest this please

**Pull request merged**
