### PR TITLE
Added wisdom

### PR DESCRIPTION
**Pull request by JSKenyon**
The intention of the PR is to implement some very rudimentary memory usage estimation. The idea will be to warn/abort if a user is going to brick their box. 

Currently this is done in a very basic way - I have derived some empirical values which I use to forecast memory usage. My data is all generated from a single MS so it currently needs testing to see if the guesses are approximately correct in all cases. In particular, it needs testing on data with a different number of antennas (my tests had 28) and more than a single direction. 

Currently this just adds a logging step and the option to error out. I will work on trying to offer sensible advice in the logs.

@PeterKamphuis @KshitijT @SpheMakh If you feel like giving this a try, please let me know. In particular, it would be incredibly useful if you could use this branch and profile your runs.

To do so, `pip install memory_profiler` and then invoke CubiCal with:
```
mprof run --include-children --multiprocess path/to/gocubical your.parset
```
Thereafter, you can run `mprof plot -1`. If you send me the CubiCal log and the plot generated by `mprof` I can rapidly see whether this approach works at all.

### CODE REVIEW

**Comment by KshitijT** [comment]
Thanks @JSKenyon ! I'll certainly give it a try.

**Comment by KshitijT** [comment]
I get this error:
```
INFO       - 13:23:10 - main               [0.1/0.1 2.9/2.9 0.0Gb] Exiting with exception: ImportError(/home/kthorat/CubiCal/cubical/kernels/rebinning.so: undefined symbol: _Py_ZeroStruct)
 Traceback (most recent call last):
  File "/home/kthorat/CubiCal/cubical/main.py", line 522, in main
    chunks_per_tile=chunks_per_tile, max_chunks_per_tile=max_chunks_per_tile)
  File "/home/kthorat/CubiCal/cubical/data_handler/ms_data_handler.py", line 990, in define_chunk
    rebinning = cubical.kernels.import_kernel("rebinning")
  File "/home/kthorat/CubiCal/cubical/kernels/__init__.py", line 56, in import_kernel
    return importlib.import_module("cubical.kernels." + name)
  File "/home/kthorat/wisdom_venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/kthorat/CubiCal/cubical/kernels/rebinning.so: undefined symbol
```
I ran the command as:
```
mprof run --include-children --multiprocess /home/kthorat/wisdom_venv/bin/gocubical sophia.parset
```

Log is here: 
[1524947605-circinus_p1_corr_2_cubical.log](https://github.com/ratt-ru/CubiCal/files/4438628/1524947605-circinus_p1_corr_2_cubical.log)

Parset from the log is here: 
[1524947605-circinus_p1_corr_2_cubical.parset.txt](https://github.com/ratt-ru/CubiCal/files/4438633/1524947605-circinus_p1_corr_2_cubical.parset.txt)

**Comment by JSKenyon** [comment]
That almost definitely has nothing g to do with my wisdom changes. Will try patch that out in the morning - I think something might be off in the setup. Sorry for the delay!

**Comment by JSKenyon** [comment]
@KshitijT I reinstalled directly from this branch into a completely fresh virtual environment and cannot reproduce your error. I had missed one requirement, but that has now been added. I seem to recall Ian having a similar issue to yours. If I remember it had something to do with using an existing/older virtual environment. Would you mind trying in a fresh one? If you are just doing this locally and not in a container, you can simply invoke the following in a fresh venv:
```
pip install cubical@git+https://github.com/ratt-ru/CubiCal.git@added_wisdom
```

**Comment by KshitijT** [comment]
> @KshitijT I reinstalled directly from this branch into a completely fresh virtual environment and cannot reproduce your error. I had missed one requirement, but that has now been added. I seem to recall Ian having a similar issue to yours. If I remember it had something to do with using an existing/older virtual environment. Would you mind trying in a fresh one? If you are just doing this locally and not in a container, you can simply invoke the following in a fresh venv:
> 
> ```
> pip install cubical@git+https://github.com/ratt-ru/CubiCal.git@added_wisdom
> ```

I'll retry. :)

It doesn't have to do anything with the specific type of environment? I made the one I am using with
`virtualenv -p python3 virtenvname`.

**Comment by JSKenyon** [comment]
That should work - I did exactly the same. The only other problem I could foresee is a missing dependency. If it errors out again, try install master in the same way. If that also breaks it likely means a prerequisite is missing. If that is the case, check out [the docs](https://cubical.readthedocs.io/en/latest/installation.html) and make sure that all the prerequisite packages are installed. Finally, if you are installing from a local copy of the repo, it might be necessary to completely delete and reclone it. The other potential issue is outdated cached numba functions. But only pursue those if a direct install from the repo into a fresh environment fails.

**Comment by KshitijT** [comment]
@JSKenyon , what is the format (name/image type) for the plot generated by memory profiler? This is how my output directory looks like:
image

**Comment by JSKenyon** [comment]
You have to make and save the plot yourself. If you ran with `mprof`, you can run `mprof list` to see all recent profiling outputs. These can be plotted with `mrpof plot ind` where ind is the integer value corresponding to the proflie you want to plot. 

That should load up a plot which you can save as a .png. Hope that helps.

**Comment by JSKenyon** [comment]
`mrpof` should have produced files with names like `mprofile_20200406112319.dat`.

**Comment by JSKenyon** [comment]
For anyone else getting involved, the `mprof` output will appear in the folder where you made the `gocubical` call.

**Comment by KshitijT** [comment]
Ok, that helped, thanks ! :)

Here are the plots: 
Figure_1
Figure_1-1

and the parset: 
[1524947605-circinus_p1_corr_2_cubical.parset.txt](https://github.com/ratt-ru/CubiCal/files/4442836/1524947605-circinus_p1_corr_2_cubical.parset.txt)

**Comment by JSKenyon** [comment]
Just to keep everyone updated, my wisdom overestimated memory usage by a factor of 3 for @KshitijT's data. I have some ideas as to why, but we will see if I can get a hold of the data to check my hunches. However, a factor of 3 is at least on the same planet as the truth so there is some hope. I would like to get the estimation accurate to roughly 10-20% though.

**Comment by JSKenyon** [comment]
Ok, I have made a little progress @KshitijT. Turns out that measurement set only has 110 unique times but they are split across 19 different scans. My estimate was naively assuming that the input values would accurately reflect the size/shape of the chunks, but CubiCal was splitting on scan by default. While my estimates are not bang on now, they are substantially closer. For whatever reason I slightly underestimate the per-worker values and slightly over-estimate the I/O value. However, we are at the low end here so estimates can be dominated by overhead. I will work on making my wisdom more aware of what is actually happening rather than relying on the user input.

**Comment by JSKenyon** [comment]
Ok, with the latest fix I get the following out of the wisdom estimate:

```
INFO       - 12:46:49 - wisdom             [0.1/0.1 0.9/0.9 0.3Gb] Detected a total of 33.52GB of system memory.
INFO       - 12:46:49 - wisdom             [0.1/0.1 0.9/0.9 0.3Gb] Per-solver (worker) memory use estimated at 0.49GB: 1.46% of total system memory.
INFO       - 12:46:49 - wisdom             [0.1/0.1 0.9/0.9 0.3Gb] Peak I/O memory use estimated at 0.42GB: 1.27% of total system memory.
INFO       - 12:46:49 - wisdom             [0.1/0.1 0.9/0.9 0.3Gb] Total peak memory usage estimated at 2.38GB: 7.10% of total system memory.
```

And the following profile output:
memuse

While this is not perfect, I am relatively happy that it is close enough to be useful. Feelings @KshitijT, @SpheMakh, @PeterKamphuis and @o-smirnov?

**Comment by JSKenyon** [comment]
retest this please

**Comment by o-smirnov** [comment]
This is very cool. I turn my head for what seems like a few minutes, and problem is solved. :)

**Comment by JSKenyon** [comment]
ok to test

**Comment by JSKenyon** [comment]
@o-smirnov can you please give this a once over - it currently only logs some info and errors out (with the option to prevent this behaviour) if the chunk and dist settings lead to an estimate exceeding the total system memory. I think this basic version is good to get into master so that we can see if it is helpful to users as well and figure out when and where its guesses are off.

**Comment by JSKenyon** [comment]
ok to test

**Comment by JSKenyon** [comment]
retest this please

**Comment by JSKenyon** [comment]
retest this please

**Comment by JSKenyon** [comment]
ok to test

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
JENKINS YOU BETTER LISTEN TO ME..... I HAVE THE POWER TO SHUT YOU DOWN!

**Comment by IanHeywood** [comment]
> JENKINS YOU BETTER LISTEN TO ME..... I HAVE THE POWER TO SHUT YOU DOWN!

I say that to my computer all the time, it never works.

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
retest this please

**Pull request merged**
